### PR TITLE
building --explorer page 🗺

### PR DESCRIPTION
**Pull request by Samuellyworld**

### CODE REVIEW

**Comment by Bhaney44** [comment]
Your API key is public. Line 47: `converter-frontend/src/components/NavBar.jsx`

 You probably want to remove that. We will still need to figure out the domain name and hosting.

**Comment by Bhaney44** [comment]
@Samuellyworld

**Comment by Samuellyworld** [comment]
Will sure remove it, i'm still buillding LFG. 🗣🔜

**Comment by Bhaney44** [comment]
> Will sure remove it, i'm still buillding LFG. 🗣🔜

LFG

**Pull request merged**
